name: Run tests

on:
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: "npm"
      - run: npm ci
      - run: OPENSSL_CONF=/dev/null npm test
